### ISSUE TITLE
configure ctests and cmake

### ISSUE THREAD

**Issue by ayaankhan98** [ayaankhan98/bigINT#5]

**Comment by VinWare** [comment]
One problem I faced is that the CMake file in tests/operators seems to take absolute paths, so it wasn't building. By commenting out AUX_SOURCE_DIRECTORY and the file statement for C files, the issue was resolved. I'll make a PR about this if you want

**Comment by ayaankhan98** [comment]
yes sure, current cmake setup is not correct. tests are also not building. if you wish to take this issue, go ahead. i have no problem

**Comment by VinWare** [comment]
OK, I'll first do this then look into the overloading

**Comment by AhsanAAR** [comment]
I don't know much about Cmake. Can I start working on bigINT directly ??

**Comment by ayaankhan98** [comment]
@AhsanAAR yes you can work, it's not necessary to know each and everything, look at the issues if you think you can work on any of these just mention there that you are working and go ahead

**Comment by AhsanAAR** [comment]
@ayaankhan98 got it. But won't I be needing it to test my cases

**Comment by ayaankhan98** [comment]
@AhsanAAR 
No CMake is not about testing, it a tool to build the project.
soon we will have automated infrastructure for building project, running tests, checking code quality and code formatting.
so you do not need to worry about this.

**Comment by AhsanAAR** [comment]
@ayaankhan98 okaa. Btw there's an issue here with gcc please take a look into this

![image](https://user-images.githubusercontent.com/39828020/95046227-388a1c80-06fd-11eb-9246-2d0e5e332e6e.png)

**Comment by ayaankhan98** [comment]
@AhsanAAR @VinWare  project structure is reconfigured and automated test and build process is also enabled now, please pull the latest changes to your fork, otherwise your PR's will have merge conflicts

**Comment by AhsanAAR** [comment]
@ayaankhan98 this problem is pertaining. it's registering int64_t and long long as the same thing

**Comment by ayaankhan98** [comment]
@AhsanAAR yes they are same, this is a bug in class definition. see #16

**Comment by AhsanAAR** [comment]
@ayaankhan98 ohkay. I'll try and resolve this issue and make a PR asap

**Comment by AhsanAAR** [comment]
@ayaankhan98 which build tool do I have to use in Cmake. Sorry if these are dumb questions I'm a bit new to open-source. But I have made a whole big float class so I can help :)

**Comment by ayaankhan98** [comment]
> @ayaankhan98 which build tool do I have to use in Cmake. Sorry if these are dumb questions I'm a bit new to open-source. But I have made a whole big float class so I can help :)

please have a look at the `readme.md`

**Comment by AhsanAAR** [comment]
@ayaankhan98 I have installed all the necessary software still getting this error 
![image](https://user-images.githubusercontent.com/39828020/95094766-b2dd8f80-0743-11eb-8a3e-5e7358f26f4b.png)

**Comment by VinWare** [comment]
@ayaankhan98 I am facing an error with one of the cmakes, which I've fixed. I'll attach the PR to this issue wait

**Comment by VinWare** [comment]
OK works now!
